-- Sample course data for testing
-- Run this after creating the schema

INSERT INTO courses (code, title, description, instructor, credits, semester, year, department, prerequisites, capacity, schedule) VALUES
('CS 101', 'Introduction to Computer Science', 'An introduction to the field of computer science, covering basic programming concepts, algorithms, and data structures.', 'Dr. Jane Smith', 3, 'Fall', 2024, 'Computer Science', '{}', 150, '{"Monday": "10:00 AM - 11:30 AM", "Wednesday": "10:00 AM - 11:30 AM"}'),
('CS 201', 'Data Structures and Algorithms', 'Advanced study of data structures and algorithms, including trees, graphs, sorting, and searching algorithms.', 'Dr. John Doe', 4, 'Fall', 2024, 'Computer Science', '{"CS 101"}', 100, '{"Tuesday": "2:00 PM - 3:30 PM", "Thursday": "2:00 PM - 3:30 PM"}'),
('MATH 101', 'Calculus I', 'Introduction to differential and integral calculus, including limits, derivatives, and applications.', 'Prof. Alice Johnson', 4, 'Fall', 2024, 'Mathematics', '{}', 200, '{"Monday": "9:00 AM - 10:30 AM", "Wednesday": "9:00 AM - 10:30 AM", "Friday": "9:00 AM - 10:00 AM"}'),
('MATH 201', 'Linear Algebra', 'Study of vector spaces, linear transformations, matrices, and systems of linear equations.', 'Prof. Bob Williams', 3, 'Fall', 2024, 'Mathematics', '{"MATH 101"}', 80, '{"Tuesday": "11:00 AM - 12:30 PM", "Thursday": "11:00 AM - 12:30 PM"}'),
('ENG 101', 'English Composition', 'Development of writing skills through practice in various forms of composition.', 'Dr. Sarah Brown', 3, 'Fall', 2024, 'English', '{}', 30, '{"Monday": "1:00 PM - 2:30 PM", "Wednesday": "1:00 PM - 2:30 PM"}'),
('PHYS 101', 'Physics I', 'Introduction to mechanics, including motion, forces, energy, and momentum.', 'Dr. Michael Green', 4, 'Fall', 2024, 'Physics', '{"MATH 101"}', 120, '{"Monday": "3:00 PM - 4:30 PM", "Wednesday": "3:00 PM - 4:30 PM", "Friday": "3:00 PM - 4:00 PM"}'),
('BIO 101', 'Introduction to Biology', 'Survey of biological concepts including cell structure, genetics, evolution, and ecology.', 'Dr. Emily White', 4, 'Fall', 2024, 'Biology', '{}', 150, '{"Tuesday": "9:00 AM - 10:30 AM", "Thursday": "9:00 AM - 10:30 AM", "Friday": "1:00 PM - 2:00 PM"}'),
('HIST 101', 'World History I', 'Survey of world history from ancient civilizations to 1500 CE.', 'Prof. David Lee', 3, 'Fall', 2024, 'History', '{}', 75, '{"Monday": "11:00 AM - 12:30 PM", "Wednesday": "11:00 AM - 12:30 PM"}'),
('PSYC 101', 'Introduction to Psychology', 'Overview of psychological principles, theories, and research methods.', 'Dr. Maria Garcia', 3, 'Fall', 2024, 'Psychology', '{}', 200, '{"Tuesday": "1:00 PM - 2:30 PM", "Thursday": "1:00 PM - 2:30 PM"}'),
('CHEM 101', 'General Chemistry I', 'Introduction to chemical principles including atomic structure, bonding, and reactions.', 'Dr. Robert Davis', 4, 'Fall', 2024, 'Chemistry', '{}', 100, '{"Monday": "8:00 AM - 9:30 AM", "Wednesday": "8:00 AM - 9:30 AM", "Friday": "11:00 AM - 12:00 PM"}');